name: Terraform Infrastructure Deployment

on:
  workflow_run:
    workflows: ["Frontend ECR Pipeline", "Backend ECR Pipeline"]
    types:
      - completed

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"
      
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      
      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check
      
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan
      
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
      
      - name: Notify success
        if: success()
        run: |
          echo "✅ Infrastructure successfully deployed with Terraform"
          echo "Frontend ECR Image: ${{ github.event.workflow_run.head_sha }}"
          echo "Backend ECR Image: ${{ github.event.workflow_run.head_sha }}" 